{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatapp.fullname" . }}-backend-secret
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodbUri | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  CLIENT_URL: {{ .Values.secrets.clientUrl | b64enc }}
{{- end }}