apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatapp.fullname" . }}-frontend
spec:
  replicas:  {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 # nginx-unprivileged user id
        fsGroup: 101

      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080

          env:
            - name: REACT_APP_API_URL
              value: "http://{{ include "chatapp.fullname" . }}-backend:5000"

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-tmp
              mountPath: /tmp

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "chatapp.fullname" . }}-frontend-config
        - name: nginx-tmp
          emptyDir: {}