apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatapp.fullname" . }}-mongo
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999

      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: {{ .Values.service.mongoPort }}

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: mongo-configdb
              mountPath: /data/configdb
            - name: mongo-tmp
              mountPath: /tmp

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ include "chatapp.fullname" . }}-mongo-pvc
        - name: mongo-configdb
          emptyDir: {}
        - name: mongo-tmp
          emptyDir: {}