apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kalaigar-Ayesha/DevSecOps-Chat-Apllication.git
    targetRevision: staging
    path: Helm
    helm:
      releaseName: chat-app-staging
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
