apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-app-backend-secret
  namespace: chat-app-dev
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    CLIENT_URL: AgBy3i4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+P
    JWT_SECRET: AgBy3i4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+P
    MONGODB_URI: AgBy3i4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+Pi4OJSWK+P
  template:
    metadata:
      name: chat-app-backend-secret
      namespace: chat-app-dev
    type: Opaque
